find_package(Git REQUIRED)

execute_process(
    COMMAND ${GIT_EXECUTABLE} describe --tags HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE PPOCRA_VERSION_STRING
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
message(STATUS ${PPOCRA_VERSION_STRING})

set(PPOCRA_VERSION_MAJOR 0)
set(PPOCRA_VERSION_MINOR 0)
set(PPOCRA_VERSION_PATCH 0)

if(${PPOCRA_VERSION_STRING} MATCHES "^v[0-9]+\\.[0-9]+\\.[0-9]+.*$")
    string(REGEX REPLACE "^v?([0-9]+).*" "\\1" PPOCRA_VERSION_MAJOR "${PPOCRA_VERSION_STRING}")
    string(REGEX REPLACE "^v?[0-9]+\\.([0-9]+).*" "\\1" PPOCRA_VERSION_MINOR "${PPOCRA_VERSION_STRING}")
    string(REGEX REPLACE "^v?[0-9]+\\.[0-9]+\\.([0-9]+).*" "\\1" PPOCRA_VERSION_PATCH "${PPOCRA_VERSION_STRING}")
endif()